<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="rover_length" value="0.302"/>
    <xacro:property name="rover_width" value="0.201"/>
    <xacro:property name="rover_height" value="0.054"/>
    <xacro:property name="rover_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.036"/>
    <xacro:property name="wheel_thickness" value="0.037"/>
    <xacro:property name="wheel_mass" value="0.04"/>
    

    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <material name="orange">
        <color rgba="1.0 0.3 0.1 1.0"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1.0 1.0"/>
    </material>

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    
    <material name="Gray">
        <color rgba="0.3 0.3 0.3 1.0"/>
    </material>

    <!-- Base Link -->
    <link name="base_link">
    </link>

    <joint name="chassis_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="chassis"/>
        <axis xyz="0.0 0.0 0.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <!-- Chassis Link-->
    <link name="chassis">
        <visual>
            <origin xyz="0.0 0.0 ${rover_height/2}" rpy="0.0 0.0 0.0"/>
            
            <geometry>
                <box size="${rover_length} ${rover_width} ${rover_height}"/>
            </geometry>

            <material name="Gray">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.01" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${rover_length} ${rover_width} ${rover_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass = "0.5"  x = "${rover_length}" y = "${rover_width}" z = "${rover_height}">
            <origin xyz="0.0 0.0 ${rover_height/2}" rpy="0.0 0.0 0.0"/>
            
        </xacro:inertial_box>
    </link>

    <gazebo reference = "chassis">
        <material>
            Gazebo/White
        </material>
    </gazebo>

    <!-- front face Link -->

    <joint name="front_face_joint" type="fixed">
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="Front"/>
        <axis xyz="0.0 0.0 0.0"/>
        <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/>
    </joint>

    <link name="Front">
        <visual>
            <origin xyz="0.12 0.0 0.04" rpy="0.0 0.0 0.0"/>
            
            <geometry>
                <box size=".02 0.02 0.02"/>
            </geometry>

            <material name="blue">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
    </link>

    <gazebo reference = "Front">
        <material>
            Gazebo/Blue
        </material>
    </gazebo>

    <!--  Front Left Wheel Link-->
    <joint name="front_left_wheel_joint" type="continuous">
        
        <parent link="base_link"/>
        <child link="front_left_wheel"/>
        <origin xyz="0.075 0.140 0.0" rpy="1.57 0.0 0.0"/>
        <axis xyz="0.0 0.0 -0.1"/>
        
            
    </joint>

    <link name="front_left_wheel">
        <visual>
            
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>

            <material name="orange">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere  radius="${wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference = "front_left_wheel">
        <material>
            Gazebo/Orange
        </material>
    </gazebo>
    

    <!-- Front Right Wheel Link -->
    <joint name="front_right_wheel_joint" type="continuous">
        
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        <origin xyz="0.075 -0.140 0.0" rpy="1.57 0.0 0.0"/>
        <axis xyz="0.0 0.0 -0.1"/>
            
    </joint>

    <link name="front_right_wheel">
        <visual>
            
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>

            <material name="orange">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere  radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>

    </link>

    <gazebo reference = "front_right_wheel">
        <material>
            Gazebo/Orange
        </material>
    </gazebo>
    

    <!-- Back Left Wheel Link  -->
    <joint name="back_left_wheel_joint" type="continuous">
        
        <parent link="base_link"/>
        <child link="back_left_wheel"/>

        <origin xyz="-0.075 0.140 0.0" rpy="1.57 0.0 0.0"/>
        <axis xyz="0.0 0.0 -0.1"/>
            
    </joint>

    <link name="back_left_wheel">
        <visual>
            
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>

            <material name="orange">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere  radius="${wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference = "back_left_wheel">
        <material>
            Gazebo/Orange
        </material>
    </gazebo>
   

    <!-- Back Right Wheel Link -->
    <joint name="back_right_wheel_joint" type="continuous">
        
        <parent link="base_link"/>
        <child link="back_right_wheel"/>

        <origin xyz="-0.075 -0.140 0.0" rpy="1.57 0.0 0.0"/>
        <axis xyz="0.0 0.0 -0.1"/>
            
    </joint>

    <link name="back_right_wheel">
        <visual>
            
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>

            <material name="orange">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere  radius="${wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" radius="${wheel_radius}" length="${wheel_thickness}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>

    </link> 

    <gazebo reference = "back_right_wheel">
        <material>
            Gazebo/Orange
        </material>
    </gazebo>
    
    </robot>
